apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: nad-lan
  namespace: mbened-dev
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "nad-lan",
      "type": "bridge",
      "bridge": "br-lan",
      "isGateway": true,
      "ipMasq": false,
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.10.0/24",
        "rangeStart": "192.168.10.10",
        "rangeEnd": "192.168.10.200",
        "gateway": "192.168.10.1"
      }
    }
